configuration:  
  projectName: receipts-service
#Receipts Service Port
server:
 port: 8092
   
logging:
 file: Receipts.log
 level: INFO
 
# MongoDB Properties 
spring:
 data:
  mongodb:
   username: dofuser
   database: ForestDB
   password: g+H1ppDyrXldSwoLBo6c6Q==
   host: localhost
   port: 27017
   uri1: mongodb://dofuser:Mzw4#12@192.168.12.137:27017,192.168.12.138:27017,192.168.12.136:27017/ForestDB?replicaSet=dof
   maxConnectionsPerHost: 10000
   threadsAllowedToBlockForConnectionMultiplier: 5
   serverSelectionTimeout: 30000
   maxWaitTime: 120000
   connectTimeout: 10000
   socketTimeout: 0
   socketKeepAlive: false
   sslEnabled: false
   sslInvalidHostNameAllowed: false
   alwaysUseMBeans: false 
   heartbeatFrequency: 10000
   minHeartbeatFrequency: 500
   heartbeatConnectTimeout: 20000
   heartbeatSocketTimeout: 20000
   localThreshold: 15
   cursorFinalizerEnabled: true
   
eureka:
  instance:
    preferIpAddress: true
   # leaseRenewalIntervalInSeconds: 1
   # leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://192.168.12.135:8761/eureka/,http://192.168.12.136:8761/eureka/
    healthcheck:
      enabled: false
  #  lease:
    #  duration: 5
